/**
 * GET /r/:code — Referral link redirect + click recorder
 *
 * WIRE-FIX (2026-08-19): this route did not exist. `recordClick()` and
 * `attributeConversion()` in @/lib/referral-engine were fully built, tested,
 * and documented as being "called from the /r/[code] redirect route" — but
 * that route was never created, so every referral link generated by
 * /api/referrals/me (`https://vantrix.ink/r/CODE`, see that route's
 * `linkPath`) 404'd, and the commission/payout pipeline downstream never
 * received any data to act on.
 *
 * Flow:
 *   1. Hash the visitor's IP+UA the same way recordClick expects, using the
 *      same IP_HASH_SALT already used for this purpose elsewhere (see
 *      /api/waitlist's identical pattern) — never store a raw IP.
 *   2. Record the click against the partner code (best-effort: an invalid
 *      or inactive code should never break navigation for the visitor).
 *   3. Redirect into the sign-up flow. Attribution itself doesn't happen
 *      here — attributeConversion() runs later, once we have a real
 *      newUserId, from POST /api/profile/ensure right after signup/sign-in
 *      (see that route). This route's only job is recording the click.
 *
 * Runs on the default Node.js runtime (not edge) because referral-engine.ts
 * imports Node's `crypto` module — same constraint that keeps /api/waitlist
 * off the edge runtime.
 */
import { NextRequest, NextResponse } from 'next/server';
import { Ratelimit }                 from '@upstash/ratelimit';
import { supabaseAdmin }             from '@/lib/supabase/admin';
import { redis }                     from '@/lib/redis';
import { getClientIp }               from '@/lib/network/get-client-ip';
import { hashVisitor, recordClick }  from '@/lib/referral-engine';
import { env }                       from '@/env';
import { logger }                    from '@/lib/logger';

export const dynamic = 'force-dynamic';

// Generous ceiling — this is a public, unauthenticated, high-traffic entry
// point (every click on every partner's shared link), not a sensitive
// action. Purpose is abuse containment, not gatekeeping real visitors.
const clickLimiter = new Ratelimit({
  redis,
  limiter:   Ratelimit.slidingWindow(60, '1 m'),
  prefix:    'rl:referral-click',
  analytics: false,
});

// Never leave a visitor stranded on a broken/typo'd referral link — always
// land them somewhere real. Sign-up is the right default: the entire point
// of a referral link is a new-user funnel, and login/page.tsx honors
// ?mode=sign-up to open straight into that form.
const SIGNUP_DESTINATION = '/login?mode=sign-up';
const FALLBACK_DESTINATION = '/';

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ code: string }> },
) {
  const { code: rawCode } = await params;
  const code = rawCode?.trim().slice(0, 64);

  const ip = getClientIp(req);
  if (ip !== null) {
    const { success } = await clickLimiter.limit(ip);
    if (!success) {
      return NextResponse.redirect(new URL(FALLBACK_DESTINATION, req.url), { status: 302 });
    }
  }

  if (!code) {
    return NextResponse.redirect(new URL(FALLBACK_DESTINATION, req.url), { status: 302 });
  }

  const userAgent = req.headers.get('user-agent') ?? 'unknown';
  const visitorHash = hashVisitor(ip ?? 'unknown', userAgent, env.IP_HASH_SALT);

  const result = await recordClick(supabaseAdmin, {
    code,
    visitorHash,
    landingPath: req.nextUrl.searchParams.get('to') ?? '/',
  });

  if ('error' in result) {
    // Invalid or inactive code — log for partner-support visibility, but
    // never expose that distinction to the visitor or block their navigation.
    logger.info('referral.click.rejected', { code, reason: result.error });
    return NextResponse.redirect(new URL(FALLBACK_DESTINATION, req.url), { status: 302 });
  }

  return NextResponse.redirect(new URL(SIGNUP_DESTINATION, req.url), { status: 302 });
}
