import type { Metadata } from "next";
import { PublicHeader } from "@/components/public/public-header";

export const metadata: Metadata = {
  title: "Terms of Service | Vantrix",
  description: "Vantrix Terms of Service.",
};

const SECTIONS: { heading: string; body: string[] }[] = [
  {
    heading: "1. Eligibility",
    body: [
      "You must be 18 or older to create a Vantrix account or use the Service. We collect a self-attested date of birth at signup and require age verification before any account can access mature content. Creating an account with a false date of birth is a violation of these Terms and grounds for immediate suspension.",
    ],
  },
  {
    heading: "2. What Vantrix is",
    body: [
      "Vantrix provides AI-generated characters you can converse with. Every character is generated by software, not operated by a human, and nothing a character says constitutes advice, a promise, or a representation of fact about the real world. Conversations, images, and other character outputs are generated in real time and may be inconsistent, inaccurate, or unexpected.",
    ],
  },
  {
    heading: "3. Your account",
    body: [
      "You're responsible for activity on your account and for keeping your login credentials secure. Let us know right away if you believe your account has been compromised.",
    ],
  },
  {
    heading: "4. Subscriptions, tokens, and billing",
    body: [
      "Paid plans and token purchases are billed through our payment processors (Stripe, Paystack, or NOWPayments depending on your region and payment method). Subscriptions renew automatically until canceled from your account settings.",
      "If a payment is refunded or disputed with your bank or payment provider, we flag the associated subscription and provide a grace period before any downgrade takes effect, so you have time to resolve a mistaken dispute with us directly before losing access.",
    ],
  },
  {
    heading: "5. Acceptable use",
    body: [
      "You agree not to use Vantrix to generate content involving minors in any sexual or romantic context, to harass or impersonate real people, to circumvent age verification or content moderation, or to use the Service for any unlawful purpose. We may suspend or terminate accounts that violate this section without notice.",
    ],
  },
  {
    heading: "6. Content moderation and safety",
    body: [
      "We use automated and human review to moderate content and enforce these Terms. If our systems detect a safety concern (including signs of crisis or self-harm risk) in a conversation, we may intervene or surface support resources.",
    ],
  },
  {
    heading: "7. Termination",
    body: [
      "You may close your account at any time from account settings. We may suspend or terminate accounts that violate these Terms, applicable law, or pose a risk to other users or the Service.",
    ],
  },
  {
    heading: "8. Disclaimers and limitation of liability",
    body: [
      "The Service is provided \"as is.\" Vantrix characters are AI-generated entertainment products, not licensed professionals, and nothing on the Service is a substitute for medical, legal, financial, or mental health advice.",
    ],
  },
  {
    heading: "9. Governing law and disputes",
    body: [
      "Vantrix is operated from the United States. These Terms are governed by the laws of the State of Delaware, without regard to conflict-of-law principles, and any dispute not subject to arbitration below will be brought exclusively in the state or federal courts located in Delaware. This applies regardless of the country you access the Service from — using Vantrix from outside the United States does not change which country's law governs these Terms.",
      "Where permitted by law, you and Vantrix agree to resolve disputes through binding individual arbitration rather than in court, except that either party may bring an individual claim in small-claims court. This section does not limit any consumer-protection rights that cannot be waived under the law of your country or state of residence.",
    ],
  },
  {
    heading: "10. Changes to these Terms",
    body: [
      "We may update these Terms from time to time. Material changes will be communicated through the app or by email before they take effect.",
    ],
  },
  {
    heading: "11. Contact",
    body: [
      "Questions about these Terms: vantrix@vantrix.ink. For general community discussion, join us on Discord (link in the footer or on our Support page) — account-specific or legal questions should go through email so we can verify your identity.",
    ],
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-base">
      <PublicHeader />
      <main className="max-w-2xl mx-auto px-4 md:px-8 py-16">
        <div className="mb-8 rounded-md border border-gold-500/40 bg-gold-500/5 px-4 py-3 text-sm text-gold-300">
          <strong className="font-semibold">Draft — pending legal review.</strong>{" "}
          This page is a structural placeholder written for engineering
          launch purposes. It has not been reviewed by counsel and should
          not be treated as final or legally binding until it is. The
          Delaware governing-law clause below is a placeholder pending
          confirmation of the entity&rsquo;s actual state of incorporation.
        </div>

        <h1 className="font-display text-3xl text-text-primary">
          Terms of Service
        </h1>
        <p className="mt-2 text-sm text-text-secondary">Last updated: draft</p>

        <div className="mt-8 space-y-7">
          {SECTIONS.map((s) => (
            <section key={s.heading}>
              <h2 className="font-display text-lg text-text-primary">
                {s.heading}
              </h2>
              {s.body.map((p, i) => (
                <p
                  key={i}
                  className="mt-2 text-[15px] leading-relaxed text-text-secondary"
                >
                  {p}
                </p>
              ))}
            </section>
          ))}
        </div>
      </main>
    </div>
  );
}
