/**
 * Backstory Content Engine — Vantrix
 *
 * knowledge-library.ts's `character_knowledge` table is the character's
 * "read history" / canon bank read into the prompt via
 * retrieveRelevantKnowledge(). Until now the only writer was
 * digital-person-bootstrap.ts, called exactly once at character creation —
 * a handful of entries auto-derived from the fields the creator already
 * typed in, then frozen forever. A character talked to daily for six
 * months has the exact same canon depth as one created five minutes ago.
 *
 * This module is the second writer: a slow-cadence, character-scoped (never
 * user-scoped — see below) generator that periodically adds ONE new
 * knowledge entry, grounded strictly in the character's own already-
 * established canon (backstory, personality, values, fears, existing
 * entries) so it reads as depth being revealed, not personality drifting.
 *
 * Deliberately character-global, not per-user:
 * `character_knowledge` has no user_id column — every user talking to this
 * character sees the same rows (see knowledge-library.ts's query). That
 * makes it structurally unsafe to ground generation in any specific user's
 * conversation history (memory_graph, priority_memories) the way
 * identity-core.ts does: one user's private confession must never become
 * canon another user's character casually references. Every input this
 * module reads is either creator-authored or previously auto-generated by
 * this same engine — nothing user-derived crosses the boundary.
 *
 * Zero manual work: no admin review queue, matching the precedent
 * digital-person-bootstrap.ts already set for this table (auto-write, no
 * gate) — every candidate still passes the platform's existing
 * moderateCharacter() gate before being stored, the same check
 * generate-chat-lines.ts uses.
 *
 * Cadence is tracked on the character row itself (`backstory_expanded_at`,
 * `backstory_expansion_count`) rather than Redis, because this is
 * character-scoped, low-frequency, and belongs next to the row it augments
 * — unlike identity-core.ts's per-(user,character) state, there's exactly
 * one of these per character.
 */

import { logger }           from '@/lib/logger';
import { supabaseAdmin }    from '@/lib/supabase/admin';
import { moderateCharacter } from '@/lib/moderation';
import { withBgSlot }       from '@/lib/ai/bg-concurrency';
import { generateStructured } from './capability';
import {
  addKnowledgeEntry,
  type KnowledgeCategory,
  type KnowledgeEntry,
} from './knowledge-library';

// Minimum days between expansions for a single character — this is meant
// to feel like a character's world slowly deepening over a long product
// lifetime, not a content mill. Combined with the cron's own batch size,
// realistic cadence is roughly one new entry every 2-4 weeks per character.
export const MIN_DAYS_BETWEEN_EXPANSIONS = 14;

// Hard ceiling — character_knowledge is prompt-injected flavor
// (retrieveRelevantKnowledge caps at MAX_INJECTED=4), not a RAG corpus;
// past this, new entries mostly waste generation budget rather than
// adding retrievable value.
export const MAX_AUTO_ENTRIES = 24;

const EXPANSION_CATEGORIES: KnowledgeCategory[] = ['backstory_detail', 'journal', 'interview'];

export interface BackstoryExpansionInput {
  id:                 string;
  name:               string;
  description:        string;
  personality:        string | null;
  backstory:          string | null;
  archetype:          string | null;
  origin:             string | null;
  occupation:         string | null;
  values_list:        string[] | null;
  fears:              string[] | null;
  is_nsfw:            boolean;
  backstory_expanded_at:     string | null;
  backstory_expansion_count: number | null;
}

interface ExistingEntrySummary {
  category: string;
  title:    string;
  tags:     string[];
}

/** Is this character due for another auto-expansion? Pure function, easy to test. */
export function isDueForExpansion(character: BackstoryExpansionInput): boolean {
  if ((character.backstory_expansion_count ?? 0) >= MAX_AUTO_ENTRIES) return false;
  if (!character.backstory_expanded_at) return true;

  const daysSince = (Date.now() - new Date(character.backstory_expanded_at).getTime()) / (1000 * 60 * 60 * 24);
  return daysSince >= MIN_DAYS_BETWEEN_EXPANSIONS;
}

interface GeneratedCandidate {
  category: KnowledgeCategory;
  title:    string;
  content:  string;
  tags:     string[];
}

async function generateCandidate(
  character: BackstoryExpansionInput,
  existing:  ExistingEntrySummary[],
): Promise<GeneratedCandidate | null> {
  const parsed = await generateStructured<Partial<GeneratedCandidate>>({
    caller: 'backstory-engine',
    maxTokens: 350,
    temperature: 0.85,
    system: `You write ONE new piece of backstory canon for a fictional AI-companion character, strictly consistent with what's given — never contradicting it, never introducing new named people/places unless clearly implied. This is internal reference material, never shown to users verbatim. Output ONLY JSON, no markdown fences:
{"category": "backstory_detail" | "journal" | "interview", "title": string (under 60 chars), "content": string (under 400 chars — for "journal" write first-person reflective; for "interview" write as if answering a question about their life; for "backstory_detail" write third-person), "tags": string[] (2-4 short lowercase keywords for retrieval matching)}
Must not duplicate the themes of any entry already listed under "existing". Never involve minors or real public figures.`,
    user: JSON.stringify({
      name:        character.name,
      description: character.description,
      personality: character.personality,
      backstory:   character.backstory,
      archetype:   character.archetype,
      origin:      character.origin,
      occupation:  character.occupation,
      values:      character.values_list,
      fears:       character.fears,
      existing:    existing.map(e => ({ category: e.category, title: e.title, tags: e.tags })),
    }),
  });

  if (!parsed?.title || !parsed.content) return null;
  const category = EXPANSION_CATEGORIES.includes(parsed.category as KnowledgeCategory)
    ? (parsed.category as KnowledgeCategory)
    : 'backstory_detail';

  return {
    category,
    title:   parsed.title.slice(0, 60),
    content: parsed.content.slice(0, 400),
    tags:    Array.isArray(parsed.tags) ? parsed.tags.filter((t): t is string => typeof t === 'string').slice(0, 4) : [],
  };
}

/**
 * Generate, moderate, and persist one new knowledge entry for a character
 * that's due (see isDueForExpansion). Returns the created entry, or null on
 * any failure/skip — always safe to call, never throws.
 */
export async function expandBackstory(
  character: BackstoryExpansionInput,
): Promise<KnowledgeEntry | null> {
  if (!isDueForExpansion(character)) return null;

  const { data: existingRows } = await supabaseAdmin
    .from('character_knowledge')
    .select('category,title,tags')
    .eq('character_id', character.id)
    .limit(50);

  const existing = (existingRows ?? []) as ExistingEntrySummary[];

  // BACKPRESSURE FIX (audit 2026-07-23): the cron route already runs this
  // sequentially within a single invocation (CHARACTERS_PER_RUN, one at a
  // time), but that doesn't protect against overlapping invocations — a
  // retried/duplicated Vercel Cron trigger, or a manual admin-triggered run
  // landing mid-schedule — each of which would run its own sequential loop
  // in parallel with no cross-invocation cap. Gating the actual OpenRouter
  // call behind the same fleet-wide slot pool used by identity-enrichment
  // closes that gap cheaply. Skip (not queue) on a full pool — this
  // character just waits for next run, same as any other isDueForExpansion
  // miss.
  const candidate = await withBgSlot('backstory-enrichment', () => generateCandidate(character, existing));
  if (!candidate) return null;

  // Same moderation gate chat-line generation uses — this is auto-written
  // canon with no human review step, so it must clear the bar every time,
  // not just at creation.
  const modResult = await moderateCharacter({ name: character.name, description: candidate.content });
  if (!modResult.allowed) {
    logger.warn('[backstory-engine] candidate rejected by moderation', {
      characterId: character.id, category: modResult.category,
    });
    return null;
  }

  const entry = await addKnowledgeEntry(character.id, {
    category: candidate.category,
    title:    candidate.title,
    content:  candidate.content,
    tags:     candidate.tags,
    weight:   45, // below bootstrap's typical seed weight — earns prominence via tag matches, not base salience
  });

  if (entry) {
    await supabaseAdmin
      .from('characters')
      .update({
        backstory_expanded_at:     new Date().toISOString(),
        backstory_expansion_count: (character.backstory_expansion_count ?? 0) + 1,
      })
      .eq('id', character.id);

    logger.info('backstory-engine:expanded', {
      characterId: character.id, category: entry.category, title: entry.title,
    });
  }

  return entry;
}
