/**
 * GET /api/notifications — SSE Real-Time In-App Notifications
 *
 * Server-Sent Events endpoint. Delivers pending character initiatives,
 * bond nudges, and secret-moment surprises (poems, letters, promise
 * follow-ups, anniversaries — see surprise-engine.ts) to the authenticated
 * user immediately on connect, then re-polls periodically and keeps the
 * connection alive with a heartbeat until it self-closes just under the
 * platform's maxDuration.
 *
 * BUG FIX (2026-08-09): this route previously only flushed pending items
 * once at connect time, then sat idle until either the client disconnected
 * or the platform killed the function — anything generated by the
 * character-initiative/surprise/nudge crons *after* connect was never
 * pushed until the client happened to reconnect. On top of that, the
 * heartbeat interval (30s) was longer than vercel.json's maxDuration for
 * this route (25s), so the first heartbeat never fired before the function
 * was hard-killed — every connection died silently and relied entirely on
 * the client's onerror handler to notice and reconnect ~10s later. Fixed
 * by: (1) polling on every tick instead of only at connect, so anything
 * new is picked up within one interval instead of only on the next
 * reconnect race, and (2) closing the stream gracefully ~2s before
 * maxDuration so the client gets a clean `close` (immediate reconnect)
 * instead of a mid-write network error.
 *
 * Client reconnects automatically on disconnect (native SSE behaviour).
 *
 * REALTIME NOTE (2026-08-20): this route is no longer the only live path
 * to the client. Every row it writes via emitNotification() below now
 * also reaches the client instantly through Supabase Realtime on the
 * `notifications` table itself (see 20260934_notifications_realtime.sql
 * + hooks/use-notifications-realtime.ts) — that's what drives the top-bar
 * bell, its dropdown, and the global toast stack now, with no 8s polling
 * delay and no dependency on this route being connected. What still only
 * exists here: `nudge` events, which are deliberately ephemeral and never
 * written to the notifications table at all (see the loop below), so
 * they have nothing for Realtime to pick up. This route's SSE stream is
 * still the delivery mechanism that writes initiative/surprise rows in
 * the first place — Realtime observes those writes, it doesn't replace
 * the polling that discovers pending ones from the AI engines.
 */
import { NextRequest, NextResponse } from 'next/server';
import { getAuthedUser } from '@/lib/auth/get-authed-user';
import { getPendingInitiatives, markInitiativeDelivered } from '@/lib/ai/character-initiative';
import { generateNudges, markNudgeSent } from '@/lib/notifications/nudge';
import { getPendingSurprises, markSurpriseDelivered } from '@/lib/ai/surprise-engine';
import { emitNotification } from '@/lib/notifications/emit';
import { supabaseAdmin } from '@/lib/supabase/admin';
import { logger, bg }     from '@/lib/logger';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

// Must stay under vercel.json's maxDuration (25s) for this route, with
// headroom for the final poll + graceful close to complete before a hard
// kill. Heartbeat/poll interval must in turn be comfortably under this so
// at least a couple of ticks land inside every connection's lifetime.
const MAX_DURATION_MS   = 25_000;
const SELF_CLOSE_AT_MS  = MAX_DURATION_MS - 2_000;
const POLL_INTERVAL_MS  = 8_000;

function sseEvent(event: string, data: unknown): Uint8Array {
  return new TextEncoder().encode(
    `event: ${event}\ndata: ${JSON.stringify(data)}\n\n`
  );
}

export async function GET(_req: NextRequest) {
  const { user } = await getAuthedUser();
  if (!user) return new Response('Unauthorized', { status: 401 });
  const userId = user.id;

  // State shared between start() and cancel()
  let intervalId: ReturnType<typeof setInterval> | undefined;
  let closeTimerId: ReturnType<typeof setTimeout> | undefined;
  let enqueue: ((chunk: Uint8Array) => void) | null = null;
  let closed = false;

  const stream = new ReadableStream({
    async start(ctrl) {
      enqueue = (chunk) => {
        try { ctrl.enqueue(chunk); } catch { /* client disconnected */ }
      };

      const pollOnce = async () => {
        // OPTIMIZE: these three fetches are fully independent (different
        // tables, no shared dependency) but were run sequentially, so each
        // poll paid the sum of all three round trips. Fetching in
        // parallel and enqueuing as each settles cuts poll latency to the
        // slowest of the three instead of the sum.
        const [initiativesResult, nudgesResult, surprisesResult] = await Promise.allSettled([
          getPendingInitiatives(userId),
          generateNudges(userId),
          getPendingSurprises(userId),
        ]);

        if (initiativesResult.status === 'fulfilled') {
          for (const initiative of initiativesResult.value) {
            enqueue!(sseEvent('initiative', {
              type:           'character_initiative',
              characterId:    initiative.characterId,
              characterName:  initiative.characterName,
              message:        initiative.message,
              urgency:        initiative.urgency,
              initiativeType: initiative.type,
              ctaUrl:         `/chat/${initiative.characterId}`,
            }));
            markInitiativeDelivered(userId, initiative.characterId, initiative.type).catch(bg('markInitiativeDelivered'));
            // Persist to the inbox + fan out push — SSE alone only reaches an
            // open tab; the inbox is what makes this durable and pushable.
            emitNotification({
              userId,
              type: 'character_initiative',
              title: initiative.characterName,
              body: initiative.message,
              ctaUrl: `/chat/${initiative.characterId}`,
              urgency: (initiative.urgency as 'low' | 'medium' | 'high') ?? 'low',
              metadata: { characterId: initiative.characterId, initiativeType: initiative.type },
            }).catch(bg('emitNotification.characterInitiative'));
          }
        } else {
          logger.warn('notifications:initiative-error', { userId, error: String(initiativesResult.reason) });
        }

        if (nudgesResult.status === 'fulfilled') {
          for (const nudge of nudgesResult.value) {
            enqueue!(sseEvent('nudge', {
              type:          'nudge',
              matchId:       nudge.matchId,
              characterName: nudge.characterName,
              message:       nudge.message,
              ctaLabel:      nudge.ctaLabel,
              ctaUrl:        nudge.ctaUrl,
              bondScore:     nudge.bondScore,
            }));
            // REPEATING-NOTIFICATION-FIX: generateNudges() (unlike the cron
            // path, generateAllPendingNudges -> markNudgesSent) never set
            // the per-match cooldown after delivering a nudge here. This
            // route polls every POLL_INTERVAL_MS (8s), so the same eligible
            // nudge — e.g. "Bianca has been thinking about you" — got
            // re-enqueued and re-shown on every single poll tick for as
            // long as the match stayed in the eligibility window, instead
            // of once per NUDGE_COOLDOWN (24h) like the cron-delivered
            // path. Mark it sent immediately after enqueuing so the next
            // poll's getEligibleNudges() correctly excludes it.
            markNudgeSent(nudge.userId, nudge.matchId).catch(bg('markNudgeSent.sse'));
          }
        } else {
          logger.warn('notifications:nudge-error', { userId, error: String(nudgesResult.reason) });
        }

        // Pending secret surprises (surprise-engine.ts) — poems, letters,
        // promise follow-ups, anniversary messages. Delivered as their own
        // event, distinct from ordinary initiatives, so the client can
        // render them with the "discovery" treatment (card / envelope)
        // rather than a plain bubble.
        if (surprisesResult.status === 'fulfilled') {
          for (const surprise of surprisesResult.value) {
            enqueue!(sseEvent('surprise', {
              type:          'character_surprise',
              characterId:   surprise.characterId,
              characterName: surprise.characterName,
              surpriseType:  surprise.type,
              message:       surprise.message,
              ctaUrl:        `/chat/${surprise.characterId}`,
            }));
            markSurpriseDelivered(surprise.id).catch(bg('markSurpriseDelivered'));
            // 'anniversary' surprises map to character_birthday; the
            // surprise engine's own 'milestone_unlocked' type maps directly;
            // everything else (promise follow-up, memory poem) is still a
            // character reaching out proactively, so it's character_initiative.
            emitNotification({
              userId,
              type: surprise.type === 'anniversary'
                ? 'character_birthday'
                : surprise.type === 'milestone_unlocked'
                  ? 'milestone_unlocked'
                  : 'character_initiative',
              title: surprise.characterName,
              body: surprise.message,
              ctaUrl: `/chat/${surprise.characterId}`,
              urgency: 'medium',
              metadata: { characterId: surprise.characterId, surpriseType: surprise.type },
            }).catch(bg('emitNotification.characterSurprise'));
          }
        } else {
          logger.warn('notifications:surprise-error', { userId, error: String(surprisesResult.reason) });
        }
      };

      // Initial flush
      await pollOnce();

      // Re-poll + heartbeat on the same tick — a ping alone told the
      // client nothing new had happened; polling here means anything a
      // cron writes mid-connection is picked up within one interval
      // instead of waiting for the next reconnect.
      intervalId = setInterval(() => {
        if (closed) return;
        pollOnce().catch(err => logger.warn('notifications:poll-error', { userId, error: String(err) }));
        try {
          ctrl.enqueue(new TextEncoder().encode(`: ping ${Date.now()}\n\n`));
        } catch {
          if (intervalId !== undefined) clearInterval(intervalId);
        }
      }, POLL_INTERVAL_MS);

      // Close cleanly before the platform kills the function, so the
      // client sees a normal `close` (and reconnects immediately) instead
      // of a mid-write error after a hard kill.
      closeTimerId = setTimeout(() => {
        closed = true;
        if (intervalId !== undefined) clearInterval(intervalId);
        try { ctrl.close(); } catch { /* already closed */ }
      }, SELF_CLOSE_AT_MS);
    },

    cancel() {
      closed = true;
      if (intervalId !== undefined) clearInterval(intervalId);
      if (closeTimerId !== undefined) clearTimeout(closeTimerId);
      enqueue = null;
    },
  });

  return new Response(stream, {
    headers: {
      'Content-Type':      'text/event-stream',
      'Cache-Control':     'no-cache, no-store',
      'Connection':        'keep-alive',
      'X-Accel-Buffering': 'no',
    },
  });
}

/**
 * DELETE /api/notifications?scope=read — bulk-clear the caller's own read
 * notifications ("Clear read" action on the notifications page). Only
 * `scope=read` is supported for now — deliberately no "delete everything
 * including unread" bulk op, so a slow-to-load client can't silently wipe
 * items the user hasn't actually seen yet; unread items go through
 * ../[id] one at a time (which also then needs to mark-read first, made
 * explicit rather than implicit here).
 */
export async function DELETE(req: NextRequest) {
  const { user } = await getAuthedUser();
  if (!user) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });

  const scope = new URL(req.url).searchParams.get('scope');
  if (scope !== 'read') {
    return NextResponse.json({ error: "Only scope=read is supported" }, { status: 400 });
  }

  const { error, count } = await supabaseAdmin
    .from('notifications')
    .delete({ count: 'exact' })
    .eq('user_id', user.id)
    .not('read_at', 'is', null);

  if (error) {
    logger.error('notifications:clear-read-error', { userId: user.id, error: error.message });
    return NextResponse.json({ error: 'Failed to clear read notifications' }, { status: 500 });
  }

  return NextResponse.json({ ok: true, count: count ?? 0 });
}
