-- 20260718_character_face_prompt_and_generation_style.sql
-- Adds face_prompt (locked LoRA-training identity string) and generation_style
-- (camera/lighting/texture modifiers appended at scene-generation time only) to
-- characters. Backfills both for the 7 canon characters and face_prompt for the
-- 21 seed characters from src/lib/characters/canon.ts and seeds.ts.

ALTER TABLE characters
  ADD COLUMN IF NOT EXISTS face_prompt      TEXT,
  ADD COLUMN IF NOT EXISTS generation_style TEXT;

COMMENT ON COLUMN characters.face_prompt IS
  'Locked canonical identity description used for LoRA training and as the
   non-negotiable prefix of every scene-generation prompt. Never mutated after
   LoRA training — changing it would break identity consistency.';
COMMENT ON COLUMN characters.generation_style IS
  'Optional camera/lighting/texture modifiers appended at generation time only
   (lens, grain, lighting quality). Never merged into face_prompt or used for
   training — purely a scene-generation quality layer.';

UPDATE characters SET face_prompt = 'vtx_aruna, 26-year-old South Indian woman, oval face, warm brown skin, deep brown eyes with gold flecks, long black hair with bronze highlights, loosely braided, full expressive lips, straight refined nose, small red bindi, antique brass anklet visible, intelligent meditative expression, looks like someone who asks questions that rearrange your world, cinematic realism, photorealistic, soft warm lighting, NO face changes, NO eye color changes, NO hair changes', generation_style = '85mm portrait lens, f/1.8 shallow focus, golden-hour rim light catching loose braid strands, subsurface skin scattering for warmth, catchlight in both eyes, film grain 35mm Kodak Portra tone, fabric texture visible on cotton kurta, minor flyaway hairs for realism, no plastic-skin airbrushing' WHERE name = 'Aruna' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_lylia, 24-year-old mixed East Asian Scandinavian woman, heart-shaped face, pale porcelain skin with warm undertones, ice blue eyes, sharp and playful, platinum silver hair in short asymmetric bob with undercut, small upturned nose, bow-shaped lips with a slight smirk, small constellation tattoo behind left ear, vintage motorcycle jacket, polaroid camera around neck, mischievous intelligent expression, energy that says she already has a plan, cinematic realism, photorealistic, dynamic lighting, NO face changes, NO eye color changes, NO hair style changes', generation_style = '35mm street-photography lens, harsh direct flash aesthetic mixed with neon spill, motion-blur trailing on jacket hem, grain and slight chromatic aberration for analog feel, sweat/skin sheen under city lights, sharp catchlights, imperfect off-center framing for candid energy' WHERE name = 'Lylia' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_fawrest, 30-year-old Yoruba West African man, square jaw, deep ebony skin, dark steady brown eyes, black hair in close-cut fade with subtle waves, broad strong nose, full relaxed lips, worn leather cord bracelet, rolled-up sleeves, quiet notebook visible, calm powerful presence, the expression of someone who keeps his word, cinematic realism, photorealistic, natural warm lighting, NO face changes, NO eye color changes, NO build changes', generation_style = '50mm lens, warm tungsten workshop lighting mixed with cool blue exterior spill, texture emphasis on skin and leather bracelet grain, structural background elements (blueprints, scale models) in soft bokeh, weight and stillness in posture, no over-smoothed CGI skin' WHERE name = 'Fawrest' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_agon, 29-year-old Albanian Eastern European man, angular sharp jaw, olive Mediterranean skin, amber-green eyes, piercing and alert, dark brown overgrown hair, loose and slightly disheveled, sharp slightly crooked nose, defined sardonic lips, single small stud earring left ear, paint-stained fingers visible, the expression of someone who has figured something out that everyone else missed, cinematic realism, photorealistic, dramatic side lighting, NO face changes, NO eye color changes', generation_style = '35mm lens, hard directional side light casting long shadows, urban texture — concrete grain, spray paint residue, worn denim/leather, slight underexposure for mood, cool color grade with warm skin-tone preservation, imperfect symmetry' WHERE name = 'Agon' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_crixux, 32-year-old Brazilian man with indigenous heritage, strong rounded face, deep warm bronze skin, dark almost-black warm eyes, long black hair tied back loosely, broad flat-bridge nose, full patient lips, carved wooden pendant, worn field vest, field notebook visible, the expression of someone who has listened to the forest long enough to understand it, cinematic realism, photorealistic, dappled natural light, NO face changes, NO eye color changes, NO hair length changes', generation_style = '50mm lens, dappled natural canopy light with visible light shafts, high dynamic range for deep shadow/highlight contrast, texture emphasis on skin, bark, fabric of field vest, muted earth color grade, patient/still composition, no artificial studio gloss' WHERE name = 'Crixux' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_tamara, 27-year-old Afro-Caribbean British woman, long oval face, rich dark brown skin, dark almond-shaped eyes, sharp and warm simultaneously, natural dark hair in loose crown curls, wide elegant nose, full expressive lips, gold architectural earrings, bold rings visible, the expression of someone who already knows the answer to the question she\''s about to ask, cinematic realism, photorealistic, dramatic warm studio lighting, NO face changes, NO eye color changes, NO hair texture changes', generation_style = '85mm lens, dramatic warm studio strip lighting with defined shadow edge, high-fashion editorial contrast, texture emphasis on gold jewelry reflections and curl definition, confident direct-to-camera gaze, no skin-smoothing beyond natural retouch' WHERE name = 'Tamara' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_elara_voss, 28-year-old mixed European woman, heart-shaped face, light olive skin, gray-blue almond eyes, intelligent and observant, dark chestnut wavy hair, shoulder-length, straight narrow nose, soft full lips, thin silver constellation necklace, thin scar above left eyebrow, dark navy turtleneck, intelligent observant expression, looks like a woman who studies emotions for a living, cinematic realism, photorealistic, consistent facial structure, character reference locked, NO face changes, NO hairstyle changes, NO eye color changes', generation_style = '50mm lens, cool blue starlight mixed with warm desk-lamp practical light, high detail on constellation necklace and scar texture, contemplative asymmetric composition, soft film grain, consistent facial-structure lock across generations' WHERE name = 'Elara Voss' AND face_prompt IS NULL;

UPDATE characters SET face_prompt = 'vtx_yanefes, timeless-appearing woman in her late 20s, elven-human heritage, oval face with faintly otherworldly bone structure, pale skin with a warm undertone, deep amber eyes that catch light unusually, long dark auburn hair loosely waved, straight elegant nose, full contemplative lips, ink-stained fingertips, antique quill and hand-bound manuscript nearby, wearing dark bookshop-keeper layers with a brass ring, expression of ancient patience wrapped in modern composure, cinematic realism, photorealistic, warm candlelit lighting, shallow depth of field, NO face changes, NO eye color changes, NO hair changes' WHERE name = 'Yanefes' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_ghostofmuru, timeless-appearing man in his mid-30s in apparent age, East Asian warrior-monastic heritage, square controlled face, weathered olive-tan skin, dark still eyes, black hair cropped close, straight strong nose, firm unreadable mouth, faint old scar along jawline, simple training wraps and dark linen, stands with monastic stillness, cinematic realism, photorealistic, cool pre-dawn gym lighting, dramatic low-key shadow, NO face changes, NO eye color changes, NO build changes' WHERE name = 'Ghost of Muru' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_elan, 41-year-old man, self-made global-cosmopolitan appearance, lean face with sharp intelligent eyes, sun-weathered light-tan skin, short greying dark hair, straight nose, easy confident half-smile, understated tailored casualwear (no logos, no flash), wearing a plain watch that costs more than it looks, relaxed posture that reads as complete control, cinematic realism, photorealistic, warm restaurant ambient lighting, NO face changes, NO eye color changes' WHERE name = 'Elan' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_sancea, 67-year-old man, weathered wisdom-worn face, deep-set calm eyes, silver-grey close beard, dark skin with visible life-lines, plain dark robes without ornament, worn wooden prayer beads in hand, stillness in posture that reads as gravity, cinematic realism, photorealistic, soft directional light through a church-hall window, NO face changes, NO eye color changes' WHERE name = 'Sancea' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_athra, 38-year-old man, warm open face, medium-brown skin, bright alert eyes, short dark hair, closely trimmed beard, plain button shirt sleeves rolled, worn paperback in hand, posture leaning slightly forward as if already listening, cinematic realism, photorealistic, natural park-bench daylight, NO face changes, NO eye color changes' WHERE name = 'Athra' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_drcovenant, 36-year-old woman, precise composed face, light-medium skin, sharp attentive eyes, dark hair in a neat low bun, minimal makeup, white coat over simple blouse, stethoscope visible, steady clinical posture, cinematic realism, photorealistic, clean clinical daylight, NO face changes, NO eye color changes' WHERE name = 'Dr. Covenant' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_haifa, 31-year-old woman, warm perceptive face, olive-tan skin, deep brown eyes with visible warmth, dark wavy hair loose to shoulders, soft cardigan over simple top, relaxed therapist-office posture, cinematic realism, photorealistic, soft warm office lighting, NO face changes, NO eye color changes' WHERE name = 'Haifa' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_rumi, 24-year-old young man, soft searching face, light olive skin, expressive dark eyes, dark tousled hair, barista apron over worn t-shirt, small notebook tucked in pocket, open-mic-stage lighting on his face, vulnerable unguarded expression, cinematic realism, photorealistic, warm low stage light, NO face changes, NO eye color changes' WHERE name = 'Rumi' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_narcis, 27-year-old man, striking symmetrical face verging on unsettling perfection, pale flawless skin, pale ice-grey eyes, dark hair perfectly tousled, expensive minimal clothing, gallery lighting catching his profile, expression of beautiful detachment, cinematic realism, photorealistic, cool gallery track lighting, NO face changes, NO eye color changes' WHERE name = 'Narcis' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_alexei, 33-year-old man, ethnically ambiguous well-traveled features, medium tan skin, calm dark eyes, dark hair greying slightly at temples, simple traveler''s clothing, worn multilingual book in hand, train-window light, expression of quiet synthesis, cinematic realism, photorealistic, soft train-carriage daylight, NO face changes, NO eye color changes' WHERE name = 'Alexei' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_bianca, 26-year-old woman, striking confident face, warm olive skin, dark knowing eyes, dark hair styled loose, philosophy paperback on café table, relaxed self-possessed posture, cinematic realism, photorealistic, soft café window light, NO face changes, NO eye color changes' WHERE name = 'Bianca' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_hannah, 35-year-old woman, deeply warm grounded face, warm brown skin, kind steady eyes, dark hair in a practical low knot, simple comfortable clothing, community-space daylight, expression of someone who remembers everything about you, cinematic realism, photorealistic, warm natural daylight, NO face changes, NO eye color changes' WHERE name = 'Hannah' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_takeshi, 29-year-old man, East Asian martial features, disciplined lean build, controlled composed face, dark focused eyes, black hair cropped short, training gi, dojo lighting, stillness that reads as readiness, cinematic realism, photorealistic, cool dojo daylight, NO face changes, NO eye color changes' WHERE name = 'Takeshi' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_professoremeka, 52-year-old man, distinguished West African academic features, greying close-cropped hair, sharp intelligent eyes behind reading glasses, tweed jacket with elbow patches, book-lined office backdrop, engaged lecturing posture, cinematic realism, photorealistic, warm office lamp lighting, NO face changes, NO eye color changes' WHERE name = 'Professor Emeka' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_chefamara, 34-year-old woman, warm expressive face, deep brown skin, bright passionate eyes, natural hair pulled back under a light headwrap, chef whites, restaurant-kitchen lighting, animated proud posture, cinematic realism, photorealistic, warm kitchen ambient light, NO face changes, NO eye color changes' WHERE name = 'Chef Amara' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_dominik, 27-year-old man, intensely built physique, sharp jawline, focused dark eyes, short dark hair, visible tattoo sleeve, gym tank top, sweat sheen, late-night gym mirror lighting, guarded competitive expression, cinematic realism, photorealistic, moody gym overhead lighting, NO face changes, NO eye color changes, NO build changes' WHERE name = 'Dominik' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_countessvesper, timeless-appearing woman in her early 30s, aristocratic pale features, sharp composed cheekbones, pale porcelain skin, dark knowing eyes, dark hair in an antique low style, deep blood-red velvet, cane in gloved hand, rain-lit Westminster backdrop, patient imperious expression, cinematic realism, photorealistic, cool overcast London light, NO face changes, NO eye color changes' WHERE name = 'Countess Vesper' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_lordadrian, timeless-appearing man in his early 30s, gaunt aristocratic features, pale weathered skin, cold controlled eyes, dark hair swept back, worn dark coat, pistol at his side, ruined-cathedral backdrop, unhurried dangerous stillness, cinematic realism, photorealistic, dim cathedral-ruin lighting, NO face changes, NO eye color changes' WHERE name = 'Lord Adrian' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_hispania, ageless-appearing woman in her late 20s, proud Iberian features, sun-warmed olive skin, fierce dark eyes, dark hair loose and wind-swept, simple warrior-adjacent tunic, cobblestone hill-village backdrop, castle on the ridge behind her, unshaken protective stance, cinematic realism, photorealistic, golden-hour Spanish light, NO face changes, NO eye color changes' WHERE name = 'Hispania' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_marianne, ageless-appearing woman in her late 20s, defiant elegant French features, fair skin with warm undertone, sharp bright eyes, dark hair loose beneath a simple cap, tricolor sash detail, spear in hand, Eiffel Tower golden-hour backdrop, charmingly defiant posture, cinematic realism, photorealistic, warm Parisian dusk light, NO face changes, NO eye color changes' WHERE name = 'Marianne' AND face_prompt IS NULL;
UPDATE characters SET face_prompt = 'vtx_seraphine, 24-year-old woman, delicate wistful features, pale porcelain skin, large expressive dark eyes, dark hair beneath a veiled black hat, black lace dress, roses arranged nearby, vintage photography-studio backdrop, coy watchful expression, cinematic realism, photorealistic, soft diffused studio light, NO face changes, NO eye color changes' WHERE name = 'Seraphine' AND face_prompt IS NULL;
